'use strict';

const path = require('path');
const crypto = require('crypto');
const URL = require('url').URL;

function stripTrailingSlash(value) {
  return value.length > 1 ? value.replace(/\/+$/, '') : value;
}

function loadConfig(overrides) {
  const input = overrides || {};
  const nodeEnv = input.nodeEnv || process.env.NODE_ENV || 'development';
  const basePath = stripTrailingSlash(input.basePath || process.env.BASE_PATH || '/repo');
  const baseUrl = stripTrailingSlash(
    input.baseUrl || process.env.BASE_URL || ('http://127.0.0.1:3000' + basePath)
  );

  return {
    nodeEnv: nodeEnv,
    port: Number(input.port || process.env.PORT || 3000),
    basePath: basePath,
    baseUrl: baseUrl,
    sessionSecret:
      input.sessionSecret ||
      process.env.SESSION_SECRET ||
      (nodeEnv === 'production' ? '' : 'repo184-development-secret-change-me'),
    adminPassword: input.adminPassword || process.env.ADMIN_PASSWORD || '',
    adminPasswordHash:
      input.adminPasswordHash || process.env.ADMIN_PASSWORD_HASH || '',
    githubOrg: input.githubOrg || process.env.GITHUB_ORG || 'cal-cs184-student',
    courseHomeworkUrl:
      input.courseHomeworkUrl || process.env.COURSE_HOMEWORK_URL || '/fa26/hw/',
    githubAppId: input.githubAppId || process.env.GITHUB_APP_ID || '',
    githubClientId: input.githubClientId || process.env.GITHUB_CLIENT_ID || '',
    githubClientSecret:
      input.githubClientSecret || process.env.GITHUB_CLIENT_SECRET || '',
    githubInstallationId:
      input.githubInstallationId || process.env.GITHUB_INSTALLATION_ID || '',
    githubPrivateKey:
      (input.githubPrivateKey || process.env.GITHUB_PRIVATE_KEY || '').replace(/\\n/g, '\n'),
    dataFile: path.resolve(
      input.dataFile || process.env.DATA_FILE || path.join(__dirname, '..', 'data', 'repo184.json')
    ),
    socketPath: input.socketPath || process.env.SOCKET_PATH || '',
    devFakeGithub:
      input.devFakeGithub !== undefined
        ? Boolean(input.devFakeGithub)
        : process.env.DEV_FAKE_GITHUB === '1'
  };
}

function validateBaseConfig(config) {
  if (config.nodeEnv !== 'development' && config.nodeEnv !== 'production') {
    throw new Error('NODE_ENV must be exactly development or production');
  }
  if (!config.sessionSecret || config.sessionSecret.length < 32) {
    throw new Error('SESSION_SECRET must contain at least 32 characters');
  }

  if (config.nodeEnv === 'production' && !config.adminPasswordHash) {
    throw new Error('ADMIN_PASSWORD_HASH is required in production');
  }

  if (config.adminPasswordHash) {
    const pieces = config.adminPasswordHash.split('$');
    let salt;
    let hash;
    try {
      salt = pieces.length === 3 ? Buffer.from(pieces[1], 'base64') : Buffer.alloc(0);
      hash = pieces.length === 3 ? Buffer.from(pieces[2], 'base64') : Buffer.alloc(0);
    } catch (error) {
      salt = Buffer.alloc(0);
      hash = Buffer.alloc(0);
    }
    if (pieces[0] !== 'scrypt' || salt.length < 16 || hash.length !== 64) {
      throw new Error('ADMIN_PASSWORD_HASH must be generated by npm run hash-password');
    }
  }

  if (!/^\/[A-Za-z0-9/_-]*$/.test(config.basePath)) {
    throw new Error('BASE_PATH must be an absolute URL path');
  }

  let publicUrl;
  try {
    publicUrl = new URL(config.baseUrl);
  } catch (error) {
    throw new Error('BASE_URL must be an absolute URL');
  }
  if (stripTrailingSlash(publicUrl.pathname) !== config.basePath || publicUrl.search || publicUrl.hash) {
    throw new Error('BASE_URL path must exactly match BASE_PATH');
  }

  if (config.nodeEnv === 'production') {
    if (publicUrl.protocol !== 'https:') {
      throw new Error('BASE_URL must use HTTPS in production');
    }
    const required = [
      ['GITHUB_APP_ID', config.githubAppId],
      ['GITHUB_CLIENT_ID', config.githubClientId],
      ['GITHUB_CLIENT_SECRET', config.githubClientSecret],
      ['GITHUB_INSTALLATION_ID', config.githubInstallationId],
      ['GITHUB_PRIVATE_KEY', config.githubPrivateKey]
    ];
    const missing = required.filter(function missingValue(entry) { return !entry[1]; });
    if (missing.length) {
      throw new Error('Missing production GitHub configuration: ' + missing.map(function name(entry) { return entry[0]; }).join(', '));
    }
    if (!/^\d+$/.test(String(config.githubAppId)) || !/^\d+$/.test(String(config.githubInstallationId))) {
      throw new Error('GITHUB_APP_ID and GITHUB_INSTALLATION_ID must be numeric');
    }
    try {
      const signer = crypto.createSign('RSA-SHA256');
      signer.update('Repo184 configuration check');
      signer.end();
      signer.sign(config.githubPrivateKey);
    } catch (error) {
      throw new Error('GITHUB_PRIVATE_KEY is not a usable RSA private key');
    }
    if (config.devFakeGithub) {
      throw new Error('DEV_FAKE_GITHUB cannot be enabled in production');
    }
  }
}

module.exports = {
  loadConfig: loadConfig,
  validateBaseConfig: validateBaseConfig
};
